### ISSUE TITLE
Windows 10 Support

### ISSUE THREAD

**Issue by elliot-labs** [koush/UniversalAdbDriver#29]
Hi, Koush,

Can you compile with native support for Windows 10?

Thanks!

**Comment by koush** [comment]
Should already work on windows 10. had reports it was fine.

**Comment by elliot-labs** [comment]
When I used it in Windows 10 (x64), it did not work for me.

**Comment by nightworks** [comment]
For me it's not working on Windows 10 either. (Windows 10 Pro x64)
The driver doesn't seem to be installed at all, at least I can't find any reference to it using driverquery

**Comment by koush** [comment]
should be fixed now.

**Comment by elliot-labs** [comment]
Thx for the info and fix, will test when I have the time.

On Wed, Aug 26, 2015, 23:16 Koushik Dutta <notifications@github.com> wrote:

> should be fixed now.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/koush/UniversalAdbDriver/issues/29#issuecomment-135271106>
> .
>
-- 
Everybody talks about the weather but they do nothing about it - Mark Twain

Elliot Huffman

DISCLAIMER:
This e-mail is for the intended recipient(s) only

If you have received it by mistake please let me know by reply and then
delete it from your system; access, disclosure, copying, distribution or
reliance on any of it by anyone else is prohibited.

If you as intended recipient have received this e-mail incorrectly, please
notify the sender (via e-mail) immediately.

**Comment by bnichlsn** [comment]
Hi Koush, I love your Vysor Beta app. It's just what I am looking for! My phone is a Samsung Galaxy S4 mini running Android 4.4.2. Vysor Beta 1.0.5.1 works on my Win7Pro PC using UniversalAdbDriver version 7.0.0.4. It no longer works with Win8.1 and has never worked with Win10. I believe that I have installed the latest UniversalAdbDriver. Do you have any suggestions?

**Comment by koush** [comment]
@bnichlsn Please open a new issue in Vysor.

https://plus.google.com/110558071969009568835/posts/1uS4nfW7xhp

**Comment by elliot-labs** [comment]
@koush I can confirm that it is now working on Windows 10 Pro x64 RTM. I tested with SGS3 (D2SPR) and sideloaded multiple ZIPs to the device.

Thank you for fixing the drivers!
